
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

sphinx:
  configuration: docs/src/conf.py

formats:
  - pdf

python:
  install:
    - requirements: docs/requirements.txt
    - method: setuptools
      path: .
