
.PHONY: clean

clean: 
	@ echo Cleaning vice/yields/agb/ 
	@ rm -f *.c 
	@ rm -f *.so 
	@ rm -rf __pycache__ 
	@ $(MAKE) -C cristallo11/ clean 
	@ $(MAKE) -C karakas10/ clean 
	@ $(MAKE) -C ventura13/ clean 
	@ $(MAKE) -C karakas16/ clean 
	@ $(MAKE) -C tests/ clean 

