
.PHONY: clean

clean: 
	@ echo Cleaning vice/yields/sneia/ 
	@ rm -f *.c 
	@ rm -f *.so 
	@ rm -rf __pycache__ 
	@ $(MAKE) -C iwamoto99/ clean 
	@ $(MAKE) -C seitenzahl13/ clean 
	@ $(MAKE) -C tests/ clean 
