
.PHONY: tests tests3 clean 

tests: 
	python test_agb_yields 
	python test_cc_yields 
	python test_dataframes 
	python test_ia_yields 
	python test_ssp 
	python test_sz_output_mirror 

tests3: 
	python3 test_agb_yields 
	python3 test_cc_yields 
	python3 test_dataframes 
	python3 test_ia_yields 
	python3 test_ssp 
	python3 test_sz_output_mirror 

clean: 
	rm -f *.out 
	rm -rf *.vice



