
.PHONY: tests tests3 clean 

tests: 
	python test_cc_yields.py 
	python test_ia_yields.py 
	python test_agb_yields.py 

tests3: 
	python3 test_cc_yields.py 
	python3 test_ia_yields.py 
	python3 test_agb_yields.py 

clean: 
	rm -f *.out 

