
.PHONY: clean 

clean: 
	$(MAKE) -C modeling/ clean 
	$(MAKE) -C objects/ clean 
	$(MAKE) -C singlezone/ clean 
	$(MAKE) -C ssp/ clean 
	$(MAKE) -C yields/ clean 
	rm -f *.pyc 
	rm -f *.out 
	rm -f *.c 
	rm -rf *.vice/ 

