
all: simulations

.PHONY: simulations clean

simulations:
	@ echo Running Johnson \& Weinberg \(2020\) simulations
	@ python simulations.py

clean:
	@ echo Cleaning starbursts/simulations/
	@ rm -rf *.vice/


