
.PHONY: clean 

clean: 
	@ echo Cleaning vice/yields/ 
	@ rm -rf __pycache__ 
	@ $(MAKE) -C agb/ clean 
	@ $(MAKE) -C ccsne/ clean 
	@ $(MAKE) -C sneia/ clean 
	@ $(MAKE) -C presets/ clean 
	@ $(MAKE) -C tests/ clean 

