
.PHONY: clean

clean: 
	@ echo Cleaning vice/yields/ccsne/ 
	@ rm -f *.c 
	@ rm -f *.so 
	@ rm -rf __pycache__ 
	@ $(MAKE) -C CL04/ clean 
	@ $(MAKE) -C CL13/ clean 
	@ $(MAKE) -C LC18/ clean 
	@ $(MAKE) -C NKT13/ clean 
	@ $(MAKE) -C WW95/ clean 
	@ $(MAKE) -C tests/ clean 

