
from __future__ import absolute_import 
__all__ = ["test"] 
from ..._globals import _RECOGNIZED_ELEMENTS_ 
from ..._globals import _DIRECTORY_ 
from ...yields import presets 
from ...yields import ccsne 
from ...yields import sneia 
from .._test_utils import moduletest 
from .._test_utils import unittest 
import os 

""" 
Changing this filename also requires changing the import line in the 
test_preset_import unittest function 
""" 
_DUMMY_FILENAME_ = "vice_dummy_preset.py" 


@moduletest
def test(): 
	""" 
	Test all preset functions 
	""" 
	return ["VICE yield preset functions", 
		[ 
			test_save(), 
			test_preset_import(), 
			test_remove() 
		] 
	] 


@unittest 
def test_save(): 
	""" 
	vice.yields.presets.save unit test 
	""" 
	def test(): 
		""" 
		Test the function which saves the yield file 
		""" 
		try: 
			spawn_dummy_yield_file() 
			presets.save(_DUMMY_FILENAME_) 
			remove_dummy_yield_file() 
		except: 
			return False 
		return True 
	return ["Save preset", test] 


@unittest 
def test_preset_import(): 
	""" 
	from vice.yields.presets import ______ unit test 
	""" 
	def test(): 
		""" 
		Test the import of the preset yield file 
		""" 
		try: 
			from vice.yields.presets import vice_dummy_preset 
		except: 
			return False 
		try: 
			for i in _RECOGNIZED_ELEMENTS_: 
				if ccsne.settings[i] != 0.001: return False 
				if sneia.settings[i] != 0.001: return False 
			ccsne.settings.restore_defaults() 
			sneia.settings.restore_defaults() 
		except: 
			return False 
		return True 
	return ["Load preset", test] 


@unittest 
def test_remove(): 
	""" 
	vice.yields.presets.remove unit test 
	""" 
	def test(): 
		""" 
		Test the function which removes the yield file 
		""" 
		try: 
			presets.remove("vice_dummy_preset.py", force = True) 
		except: 
			return False 
		return "vice_dummy_preset.py" not in os.listdir("%syields/presets/" % (
			_DIRECTORY_)) 
	return ["Remove preset", test] 


def spawn_dummy_yield_file(filename = _DUMMY_FILENAME_): 
	""" 
	Generate a dummy yield file that sets all CCSN and SN Ia yields to 0.001 
	""" 
	cnt = """\

# This file generated by vice/tests/preset.py 
import vice 
for i in vice._globals._RECOGNIZED_ELEMENTS_: 
	vice.yields.ccsne.settings[i] = 0.001 
	vice.yields.sneia.settings[i] = 0.001 

""" 
	os.system("echo \'%s\' >> %s" % (cnt, filename)) 


def remove_dummy_yield_file(filename = _DUMMY_FILENAME_): 
	""" 
	Remove the dummy yield file 
	""" 
	os.system("rm -f %s" % (filename)) 

