""" 
This file implements the sources built-in dataframe 
""" 

from __future__ import absolute_import 
from .._builtin_elemental_data import builtin_elemental_data 


#----------------------------- SOURCES DATAFRAME -----------------------------# 
sources = builtin_elemental_data({
	"he": 		["BBN", "CCSNE", "AGB"], 
	"c":		["CCSNE", "AGB"], 
	"n":		["CCSNE", "AGB"], 
	"o":		["CCSNE"], 
	"f": 		["CCSNE"], 
	"ne":		["CCSNE"], 
	"na":		["CCSNE"], 
	"mg":		["CCSNE"], 
	"al":		["CCSNE"], 
	"si":		["CCSNE", "SNEIA"], 
	"p":		["CCSNE", "SNEIA"], 
	"s":		["CCSNE", "SNEIA"], 
	"cl":		["CCSNE", "SNEIA"], 
	"ar":		["CCSNE", "SNEIA"], 
	"k": 		["CCSNE", "SNEIA"], 
	"ca": 		["CCSNE", "SNEIA"], 
	"sc": 		["CCSNE", "SNEIA"], 
	"ti": 		["CCSNE", "SNEIA"], 
	"v": 		["CCSNE", "SNEIA"], 
	"cr": 		["CCSNE", "SNEIA"], 
	"mn": 		["CCSNE", "SNEIA"], 
	"fe":		["CCSNE", "SNEIA"], 
	"co": 		["CCSNE", "SNEIA"], 
	"ni": 		["CCSNE", "SNEIA"], 
	"cu": 		["CCSNE", "SNEIA"], 
	"zn": 		["CCSNE", "SNEIA"], 
	"ga": 		["CCSNE"], 
	"ge": 		["CCSNE"], 
	"as": 		["CCSNE"], 
	"se": 		["CCSNE"], 
	"br":		["CCSNE"], 
	"kr": 		["CCSNE"], 
	"rb": 		["CCSNE"], 
	"sr":		["CCSNE", "AGB"], 
	"y":		["CCSNE", "AGB"], 
	"zr": 		["CCSNE", "AGB"], 
	"nb": 		["AGB", "NSNS"], 
	"mo": 		["AGB", "NSNS"], 
	"ru": 		["AGB", "NSNS"], 
	"rh":		["AGB", "NSNS"], 
	"pd": 		["AGB", "NSNS"], 
	"ag": 		["AGB", "NSNS"], 
	"cd": 		["AGB", "NSNS"], 
	"in": 		["AGB", "NSNS"], 
	"sn": 		["AGB", "NSNS"], 
	"sb":		["AGB", "NSNS"], 
	"te": 		["AGB", "NSNS"], 
	"i": 		["AGB", "NSNS"], 
	"xe": 		["AGB", "NSNS"], 
	"cs": 		["AGB", "NSNS"], 
	"ba":		["AGB", "NSNS"],
	"la":		["AGB", "NSNS"], 
	"ce": 		["AGB", "NSNS"], 
	"pr": 		["AGB", "NSNS"], 
	"nd": 		["AGB", "NSNS"], 
	"sm": 		["AGB", "NSNS"], 
	"eu":		["AGB", "NSNS"], 
	"gd": 		["AGB", "NSNS"], 
	"tb": 		["AGB", "NSNS"], 
	"dy": 		["AGB", "NSNS"], 
	"ho": 		["AGB", "NSNS"], 
	"er": 		["AGB", "NSNS"], 
	"tm": 		["AGB", "NSNS"], 
	"yb": 		["AGB", "NSNS"], 
	"lu": 		["AGB", "NSNS"], 
	"hf": 		["AGB", "NSNS"], 
	"ta": 		["AGB", "NSNS"], 
	"w": 		["AGB", "NSNS"], 
	"re": 		["AGB", "NSNS"], 
	"os": 		["AGB", "NSNS"], 
	"ir": 		["AGB", "NSNS"], 
	"pt": 		["AGB", "NSNS"], 
	"au": 		["AGB", "NSNS"], 
	"hg":		["AGB", "NSNS"], 
	"tl": 		["AGB", "NSNS"], 
	"pb": 		["AGB", "NSNS"], 
	"bi": 		["AGB", "NSNS"] 
}, "source") 

