# This workflow creates a source distribution intended for uploading to PyPI,
# uploading the .tar.gz file to GitHub actions as an artifact. We upload the
# source distribution to PyPI manually. In previous versions of VICE, we
# pre-compiled the code and provided the binaries, but we have scaled this down
# for reasons described in the comments in the wheels.yml workflow file.
# Previously, the wheels.yml workflow would download this source distribution
# and combine it with the wheels created by bdist_linux.yml and bdist_macos.yml.

name: Source Distribution

# only when specifically requested
on:
  workflow_dispatch:
  ### previous inputs from wheels.yml, which would call this workflow ###
  # workflow_call:
  #   inputs:
  #     os:
  #       description: The OS to use for creating the source distribution
  #       required: true
  #       type: string
  #     python-version:
  #       description: The version of python for creating the source distribution
  #       required: true
  #       type: string

jobs:
  sdist:
    name: Source Distribution
    runs-on: ubuntu-latest
    ### previous inputs from wheels.yml, which would call this workflow ###
    # runs-on: ${{ inputs.os }}
    # env:
    #   COMPILER: gcc

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      ### previous inputs from wheels.yml, which would call this workflow ###
      # - name: Setup Python ${{ inputs.python-version }}
      #   uses: actions/setup-python@v2
      #   with:
      #     python-version: ${{ inputs.python-version }}

      - name: Setup Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install Dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
          python -m pip install setuptools>=18.0
          python -m pip install Cython>=3.0
          python -m pip install wheel>=0.33.0

      - name: Display Environment Variables
        shell: bash
        run: |
          echo "PATH: " $PATH
          echo "COMIPLER: " `which $COMPILER`
          echo "COMPILER VERSION: " `$COMPILER --version`
          echo "PYTHON: " `which python`
          echo "PYTHON VERSION: " `python --version`
          echo "MAKE: " `which make`
          echo "MAKE VERSION: " `make --version`

      - name: Create Source Distribution
        shell: bash
        run: |
          python -m build --sdist

      - name: Upload Source Distribution
        uses: actions/upload-artifact@v2
        with:
          name: sdist
          path: ./dist/*.tar.gz
          retention-days: 1

