# This workflow pre-compiles VICE for distribution across all versions of
# python supported by the code base. Requiring a 64-bit system architecture,
# we pre-compile for x86_64 hardware on both Mac OS and Linux. As of yet,
# GitHub Actionos does not provide support for cloud-hosted virtual machines
# on ARM64 hardware. This includes the Apple M1 chips (Apple Silicon) as well
# as Aarch64 Linux machines. We do not yet pre-compile VICE for ARM hardware,
# though an installation from source is straight-forward and fast on these
# machines.
# 
# At present, GitHub actions does not support a build matrix for jobs that
# call a reusable workflow, so the Mac OS and manylinux jobs here implement
# the workaround from the following URL: 
# 
# https://github.community/t/reusable-workflow-with-strategy-matrix/205676/8

name: PyPI Wheels

# only when specifically requested
on:
  workflow_dispatch:

jobs:

  ##### Source distribution -> prepared using the Ubuntu VM #####
  sdist:
    uses: giganano/VICE/.github/workflows/sdist.yml@main
    with:
      os: ubuntu-20.04
      python-version: "3.9"

  ##### Mac OS distributions for >= 10.9 on x86_64 hardware #####
  macos_x86_64:
    uses: giganano/VICE/.github/workflows/bdist_macos.yml@main
    with:
      python-versions: >-
        ["3.6", "3.7", "3.8", "3.9", "3.10"]
      wheel-name: macos_x86_64

  ##### manylinux2014 distribution on x86_64 hardware #####
  manylinux2014_x86_64:
    uses: giganano/VICE/.github/workflows/bdist_linux.yml@main
    with:
      python-versions: >-
        ["cp36-cp36m", "cp37-cp37m", "cp38-cp38", "cp39-cp39", "cp310-cp310"]
      wheel-name: manylinux2014_x86_64
      image: docker://quay.io/pypa/manylinux2014_x86_64

  ##### manylinux_2_24 distribution on x86_64 hardware #####
  manylinux_2_24_x86_64:
    uses: giganano/VICE/.github/workflows/bdist_linux.yml@main
    with:
      python-versions: >-
        ["cp36-cp36m", "cp37-cp37m", "cp38-cp38", "cp39-cp39", "cp310-cp310"]
      wheel-name: manylinux_2_24_x86_64
      image: docker://quay.io/pypa/manylinux_2_24_x86_64

  # Combines the zipfiles containing the wheels and the source distribution
  # 
  # An action which deletes workflow artifacts is in development by GitHub.
  # Once released, this workflow should delete previous artifacts and leave
  # behind only the one zipfile containing all of the wheels.
  combine_zipfiles:
    name: Combine Wheel Zipfiles
    needs: [sdist, macos_x86_64, manylinux2014_x86_64, manylinux_2_24_x86_64]
    runs-on: ubuntu-20.04

    steps:
      - name: Download Source Distribution
        uses: actions/download-artifact@v2
        with:
          name: sdist

      - name: Download Mac OS Wheels
        uses: actions/download-artifact@v2
        with:
          name: macos_x86_64

      - name: Download manylinux2014_x86_64 Wheels
        uses: actions/download-artifact@v2
        with:
          name: manylinux2014_x86_64

      - name: Download manylinux_2_24_x86_64 Wheels
        uses: actions/download-artifact@v2
        with:
          name: manylinux_2_24_x86_64

      - name: Upload Files
        uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: |
            ./*.whl
            ./*.tar.gz
          retention-days: 5

